name = "sharex-r2-cloudflare-workers"
account_id = "c0baa3ca2bbd1100ab7104f0ae5e48be"
workers_dev = true
routes = [
	{pattern = "r2-sharex.jross.me/*", zone_name = "jross.me"},
	{pattern = "i.james.pub/*", zone_name = "james.pub"}
]

compatibility_date = "2022-10-31"
compatibility_flags = ["nodejs_compat"]
main = "./dist/index.mjs"

[build]
command = "npm run build"

[[r2_buckets]]
bucket_name = "s-files"
preview_bucket_name = "s-files"
binding = "R2_BUCKET"

[vars]
# Change to the domain your Public Bucket is connected to.
#CUSTOM_PUBLIC_BUCKET_DOMAIN = "custom-bucket.domain.tld"
# Change to not let the worker serve files, only allowing traffic through the Public Bucket. Do not set if you have old links pointing to the worker.
#ONLY_ALLOW_ACCESS_TO_PUBLIC_BUCKET = true
